homepage:
  images:
    directories: [homepage/images]
    extensions: [jpg, png]
  css:
    directories: [homepage/css]
    extensions: [css]
  rules:
    pathContains: /homepage
dashboard:
  javascript:
    directories: [dashboard/js]
    extensions: [js]
  rules:
    query:
      admin: true
      user:
        regex: /^user[0-9]+$/