homepage:
  images:
    directories: [tests/bundles/homepage/images]
    extensions: [jpg, png]
  css:
    directories: [tests/bundles/homepage/css]
    extensions: [css]
  rules:
    pathContains: /homepage

dashboard:
  javascript:
    directories: [tests/bundles/dashboard/js]
    extensions: [js]
  rules:
    query:
      admin: true
