name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Specify the PHP version you want to use

      - name: Install Composer dependencies
        run: cd AssetGatherer && composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHPUnit tests
        run: cd AssetGatherer && vendor/bin/phpunit ./tests/
